export const ARTISTS_LIST_REQUEST = "ARTISTS_LIST_REQUEST";
export const ARTISTS_LIST_SUCCESS = "ARTISTS_LIST_SUCCESS";
export const ARTISTS_LIST_FAIL = "ARTISTS_LIST_FAIL";

export const ARTIST_DETAILS_REQUEST = "ARTIST_DETAILS_REQUEST";
export const ARTIST_DETAILS_SUCCESS = "ARTIST_DETAILS_SUCCESS";
export const ARTIST_DETAILS_FAIL = "ARTIST_DETAILS_FAIL";
export const ARTIST_DETAILS_RESET = "ARTIST_DETAILS_RESET";

export const DELETE_ARTIST_REQUEST = "DELETE_ARTIST_REQUEST";
export const DELETE_ARTIST_SUCCESS = "DELETE_ARTIST_SUCCESS";
export const DELETE_ARTIST_FAIL = "DELETE_ARTIST_FAIL";

export const UPDATE_ARTIST_REQUEST = "UPDATE_ARTIST_REQUEST";
export const UPDATE_ARTIST_SUCCESS = "UPDATE_ARTIST_SUCCESS";
export const UPDATE_ARTIST_FAIL = "UPDATE_ARTIST_FAIL";
export const UPDATE_ARTIST_RESET = "UPDATE_ARTIST_RESET";